/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pastime.cash;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author gabriel_f_junkes
 */
public class Cadastro extends javax.swing.JFrame {
        private static int jaPassouNome=0;
        private static int jaPassouEmail=0;
        private static int jaPassouUsuario=0;
        private static int jaPassouSenha=0;
        private static int jaPassouSenha1=0;
    /**
     * Creates new form Cadastro
     */
    public Cadastro() {
        initComponents();
        setSize(485,355);
        jaPassouSenha=0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtSenha1 = new javax.swing.JPasswordField();
        txtSenha = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        ckTermos = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cadastro");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 160, -1));

        jLabel3.setForeground(new java.awt.Color(51, 153, 255));
        jLabel3.setText("Termos e Condições de Uso");
        jLabel3.setToolTipText("Termos e Condições");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 170, -1));

        txtUsuario.setForeground(new java.awt.Color(153, 153, 153));
        txtUsuario.setText("Usuário"); // NOI18N
        txtUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUsuarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUsuarioFocusLost(evt);
            }
        });
        getContentPane().add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 350, 24));

        txtNome.setForeground(new java.awt.Color(153, 153, 153));
        txtNome.setText("Nome Completo");
        txtNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNomeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNomeFocusLost(evt);
            }
        });
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        getContentPane().add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 350, 24));

        txtEmail.setForeground(new java.awt.Color(153, 153, 153));
        txtEmail.setText("Email");
        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmailFocusLost(evt);
            }
        });
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 350, 24));

        txtSenha1.setForeground(new java.awt.Color(153, 153, 153));
        txtSenha1.setText("Senha");
        txtSenha1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSenha1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSenha1FocusLost(evt);
            }
        });
        getContentPane().add(txtSenha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 350, 24));

        txtSenha.setForeground(new java.awt.Color(153, 153, 153));
        txtSenha.setText("senha"); // NOI18N
        txtSenha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSenhaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSenhaFocusLost(evt);
            }
        });
        getContentPane().add(txtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 350, 24));

        jButton1.setBackground(new java.awt.Color(255, 102, 102));
        jButton1.setText("Limpa campos");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 130, 24));

        jButton2.setBackground(new java.awt.Color(153, 255, 153));
        jButton2.setText("Registrar");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, 110, 24));

        ckTermos.setForeground(new java.awt.Color(255, 255, 255));
        ckTermos.setText("Li e concordo com os");
        ckTermos.setBorder(null);
        ckTermos.setContentAreaFilled(false);
        getContentPane().add(ckTermos, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 140, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pastime/cash/Imagens/voltar pagina branco.png"))); // NOI18N
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pastime/cash/Imagens/fundo cadastro logado.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jTextField1.setText("jTextField1");
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        JOptionPane.showMessageDialog(null, "Esse termo da acesso ao Aplicativo PastTime Cash,\n"
                + "com uma licença revogável, não exclusiva e intransferível de uso do Aplicativo.  \n"
                + "Ao assinar você estará concordando também com os termos de uso, sendo eles:\n"
                + "- Respeitar o proximo;\n"
                + "- Seguir as regras dos estabelecimentos indicados. ");
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        Login login = new Login();
        dispose();
        login.setVisible(true);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       txtNome.setText("Nome Completo");
       txtNome.setForeground(Color.gray);
       txtEmail.setText("Email");
       txtEmail.setForeground(Color.gray);
       txtUsuario.setText("Usuário");
       txtUsuario.setForeground(Color.gray);
       txtSenha.setText("Senha");
       txtSenha.setForeground(Color.gray);
       txtSenha1.setText("Senha");
       txtSenha1.setForeground(Color.gray);
       ckTermos.setSelected(false);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String nome = txtNome.getText();
        String email = txtEmail.getText();
        String usuario = txtUsuario.getText();
        String senha = txtSenha.getText();
        String confirmaSenha = txtSenha1.getText();
        boolean termos = ckTermos.isSelected();
        
        if((nome.equals("")) || nome.equals("Nome Completo") ||(email.equals("")) || email.equals("Email") ||(usuario.equals("")) || usuario.equals("Usuário") ||(senha.equals("")) || senha.equals("Senha") ||(confirmaSenha.equals("")) || confirmaSenha.equals("Senha")){
            JOptionPane.showMessageDialog(null, "Preencha todos os campos!");   
        }else if(termos==false){
            JOptionPane.showMessageDialog(null,"Para realizar o cadastro é necessário ler e concordar com os Termos e Condições de Uso.");
        }else if(!senha.equals(confirmaSenha)){
            JOptionPane.showMessageDialog(null, "Senha inválida!");
        }else if(!email.contains("@")){
            JOptionPane.showMessageDialog(null, "Informe um e-mail válido!");
        }else{ 
            ArmazenaUsuario.senha=confirmaSenha;
            ArmazenaUsuario.nome = nome;
            ArmazenaUsuario.email = email;
            ArmazenaUsuario.usuario = usuario;
            ArmazenaUsuario.saldo=0;
            ArmazenaUsuario.nascimento="";
            ArmazenaUsuario.sexo="";
            ArmazenaUsuario.imagemDiretorio="";
             
             dispose();
           Quiz quiz = new Quiz();
           quiz.setVisible(true);
       
            
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtNomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomeFocusGained
        String nome = txtNome.getText();
        if (nome.equals("Nome Completo")){
            jaPassouNome=0;
        }
        switch (jaPassouNome){
            case 0:
                txtNome.setText("");
                txtNome.setForeground(Color.black);
                jaPassouNome=1;
                break;
        }
    }//GEN-LAST:event_txtNomeFocusGained

    private void txtEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusGained
        String nome = txtEmail.getText();
        if (nome.equals("Email")){
            jaPassouEmail=0;
        }
        switch (jaPassouEmail){
            case 0:
                txtEmail.setText("");
                txtEmail.setForeground(Color.black);
                jaPassouEmail=1;
                break;
        }
    }//GEN-LAST:event_txtEmailFocusGained

    private void txtUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsuarioFocusGained
        String usuario = txtUsuario.getText();
        if (usuario.equals("Usuário")){
            jaPassouUsuario=0;
        }
        switch (jaPassouUsuario){
            case 0:
                txtUsuario.setText("");
                txtUsuario.setForeground(Color.black);
                jaPassouUsuario=1;
                break;
        }
    }//GEN-LAST:event_txtUsuarioFocusGained

    private void txtSenhaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSenhaFocusGained
        String senha = txtSenha.getText();
        if (senha.equals("Senha")){
            jaPassouSenha=0;
        }
        switch (jaPassouSenha){
            case 0:
                txtSenha.setText("");
                txtSenha.setForeground(Color.black);
                jaPassouSenha=1;
                break;
        }
    }//GEN-LAST:event_txtSenhaFocusGained

    private void txtSenha1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSenha1FocusGained
        String senha1 = txtSenha1.getText();
        if (senha1.equals("Senha")){
            jaPassouSenha1=0;
        }
        switch (jaPassouSenha1){
            case 0:
                txtSenha1.setText("");
                txtSenha1.setForeground(Color.black);
                jaPassouSenha1=1;
                break;
        }
    }//GEN-LAST:event_txtSenha1FocusGained

    private void txtNomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomeFocusLost
        String nome = txtNome.getText();
        if (nome.equals("")){
            txtNome.setText("Nome Completo");
            txtNome.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtNomeFocusLost

    private void txtEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusLost
        String email = txtEmail.getText();
        if (email.equals("")){
            txtEmail.setText("Email");
            txtEmail.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtEmailFocusLost

    private void txtSenhaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSenhaFocusLost
        String senha = txtSenha.getText();
        if (senha.equals("")){
            txtSenha.setText("Senha");
            txtSenha.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtSenhaFocusLost

    private void txtUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsuarioFocusLost
        String usuario = txtUsuario.getText();
        if (usuario.equals("")){
            txtUsuario.setText("Usuário");
            txtUsuario.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtUsuarioFocusLost

    private void txtSenha1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSenha1FocusLost
        String senha = txtSenha1.getText();
        if (senha.equals("")){
            txtSenha1.setText("Senha");
            txtSenha1.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtSenha1FocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox ckTermos;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNome;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JPasswordField txtSenha1;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
