/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pastime.cash;

import javax.swing.JOptionPane;

/**
 *
 * @author gabriel_f_junkes
 */
public class Hobbies extends javax.swing.JFrame {

    public void VerificaHobbies(){
        if (ArmazenaUsuario.basquete){
            jcBasquete.setSelected(true);
        }else {
            jcBasquete.setSelected(false);
        }
        
        if (ArmazenaUsuario.futebol){
            jcFutebol.setSelected(true);
        }else {
            jcFutebol.setSelected(false);
        }
        
        if (ArmazenaUsuario.volei){
            jcVolei.setSelected(true);
        }else {
            jcVolei.setSelected(false);
        }
        
        if (ArmazenaUsuario.tenis){
            jcTenis.setSelected(true);
        }else {
            jcTenis.setSelected(false);
        }
        
        if (ArmazenaUsuario.natacao){
            jcNatacao.setSelected(true);
        }else {
            jcNatacao.setSelected(false);
        }
        
        if (ArmazenaUsuario.ciclismo){
            jcCiclismo.setSelected(true);
        }else {
            jcCiclismo.setSelected(false);
        }
        
        if (ArmazenaUsuario.corrida){
            jcCorrida.setSelected(true);
        }else {
            jcCorrida.setSelected(false);
        }
        
        if (ArmazenaUsuario.caminhada){
            jcCaminhada.setSelected(true);
        }else {
            jcCaminhada.setSelected(false);
        }
        
        if (ArmazenaUsuario.trilha){
            jcTrilha.setSelected(true);
        }else {
            jcTrilha.setSelected(false);
        }
        
        if (ArmazenaUsuario.passeio){
            jcPasseio.setSelected(true);
        }else {
            jcPasseio.setSelected(false);
        }
        
    }
    public Hobbies() {
        initComponents();
        setSize(550,420);
        VerificaHobbies();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jcVolei = new javax.swing.JCheckBox();
        jcBasquete = new javax.swing.JCheckBox();
        jcFutebol = new javax.swing.JCheckBox();
        jcTenis = new javax.swing.JCheckBox();
        jcNatacao = new javax.swing.JCheckBox();
        jcCiclismo = new javax.swing.JCheckBox();
        jcCorrida = new javax.swing.JCheckBox();
        jcCaminhada = new javax.swing.JCheckBox();
        jcTrilha = new javax.swing.JCheckBox();
        jcPasseio = new javax.swing.JCheckBox();
        bContinuar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jcVolei.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jcVolei.setText("Vôlei");
        jcVolei.setToolTipText("");
        jcVolei.setBorder(null);
        jcVolei.setContentAreaFilled(false);
        jcVolei.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcVoleiActionPerformed(evt);
            }
        });
        jPanel1.add(jcVolei, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        jcBasquete.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jcBasquete.setText("Basquete");
        jcBasquete.setToolTipText("");
        jcBasquete.setBorder(null);
        jcBasquete.setContentAreaFilled(false);
        jcBasquete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcBasqueteActionPerformed(evt);
            }
        });
        jPanel1.add(jcBasquete, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        jcFutebol.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jcFutebol.setText("Futebol");
        jcFutebol.setToolTipText("");
        jcFutebol.setBorder(null);
        jcFutebol.setContentAreaFilled(false);
        jcFutebol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcFutebolActionPerformed(evt);
            }
        });
        jPanel1.add(jcFutebol, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        jcTenis.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jcTenis.setText("Tênis");
        jcTenis.setToolTipText("");
        jcTenis.setBorder(null);
        jcTenis.setContentAreaFilled(false);
        jcTenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcTenisActionPerformed(evt);
            }
        });
        jPanel1.add(jcTenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        jcNatacao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jcNatacao.setText("Natação");
        jcNatacao.setToolTipText("");
        jcNatacao.setBorder(null);
        jcNatacao.setContentAreaFilled(false);
        jcNatacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcNatacaoActionPerformed(evt);
            }
        });
        jPanel1.add(jcNatacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, -1, -1));

        jcCiclismo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jcCiclismo.setText("Ciclismo");
        jcCiclismo.setToolTipText("");
        jcCiclismo.setBorder(null);
        jcCiclismo.setContentAreaFilled(false);
        jcCiclismo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcCiclismoActionPerformed(evt);
            }
        });
        jPanel1.add(jcCiclismo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, -1, -1));

        jcCorrida.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jcCorrida.setText("Corrida");
        jcCorrida.setToolTipText("");
        jcCorrida.setBorder(null);
        jcCorrida.setContentAreaFilled(false);
        jcCorrida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcCorridaActionPerformed(evt);
            }
        });
        jPanel1.add(jcCorrida, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, -1, -1));

        jcCaminhada.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jcCaminhada.setText("Caminhada");
        jcCaminhada.setToolTipText("");
        jcCaminhada.setBorder(null);
        jcCaminhada.setContentAreaFilled(false);
        jcCaminhada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcCaminhadaActionPerformed(evt);
            }
        });
        jPanel1.add(jcCaminhada, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, -1, -1));

        jcTrilha.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jcTrilha.setText("Trilha");
        jcTrilha.setToolTipText("");
        jcTrilha.setBorder(null);
        jcTrilha.setContentAreaFilled(false);
        jcTrilha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcTrilhaActionPerformed(evt);
            }
        });
        jPanel1.add(jcTrilha, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, -1, -1));

        jcPasseio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jcPasseio.setText("Passeio");
        jcPasseio.setToolTipText("");
        jcPasseio.setBorder(null);
        jcPasseio.setContentAreaFilled(false);
        jcPasseio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcPasseioActionPerformed(evt);
            }
        });
        jPanel1.add(jcPasseio, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 470, 330));

        bContinuar.setBackground(new java.awt.Color(0, 102, 0));
        bContinuar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bContinuar.setForeground(new java.awt.Color(255, 255, 255));
        bContinuar.setText("Continuar");
        bContinuar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bContinuar.setBorderPainted(false);
        bContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bContinuarActionPerformed(evt);
            }
        });
        getContentPane().add(bContinuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 350, 110, 24));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/perguntaIcon.png"))); // NOI18N
        jLabel1.setToolTipText("Aqui você pode selecionar ou desselecionar os hobbies.");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));

        Fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pastime/cash/Imagens/fundo corrida verde.png"))); // NOI18N
        getContentPane().add(Fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-130, -30, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jcVoleiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcVoleiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcVoleiActionPerformed

    private void jcBasqueteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcBasqueteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcBasqueteActionPerformed

    private void jcFutebolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcFutebolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcFutebolActionPerformed

    private void jcTenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcTenisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcTenisActionPerformed

    private void jcNatacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcNatacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcNatacaoActionPerformed

    private void jcCiclismoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcCiclismoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcCiclismoActionPerformed

    private void jcCorridaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcCorridaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcCorridaActionPerformed

    private void jcCaminhadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcCaminhadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcCaminhadaActionPerformed

    private void jcTrilhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcTrilhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcTrilhaActionPerformed

    private void jcPasseioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcPasseioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcPasseioActionPerformed

    private void bContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bContinuarActionPerformed
        ArmazenaUsuario.basquete=jcBasquete.isSelected();
        ArmazenaUsuario.futebol=jcFutebol.isSelected();
        ArmazenaUsuario.volei=jcVolei.isSelected();
        ArmazenaUsuario.tenis=jcTenis.isSelected();
        ArmazenaUsuario.natacao=jcNatacao.isSelected();
        ArmazenaUsuario.ciclismo=jcCiclismo.isSelected();
        ArmazenaUsuario.corrida=jcCorrida.isSelected();
        ArmazenaUsuario.caminhada=jcCaminhada.isSelected();
        ArmazenaUsuario.trilha=jcTrilha.isSelected();
        ArmazenaUsuario.passeio=jcPasseio.isSelected();
        Perfil perfil = new Perfil();
        dispose();
        perfil.setVisible(true);
    }//GEN-LAST:event_bContinuarActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
//        JOptionPane.showMessageDialog(null, "Aqui você pode selecionar ou desselecionar os hobbies.");
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hobbies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hobbies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hobbies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hobbies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hobbies().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fundo;
    private javax.swing.JButton bContinuar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox jcBasquete;
    private javax.swing.JCheckBox jcCaminhada;
    private javax.swing.JCheckBox jcCiclismo;
    private javax.swing.JCheckBox jcCorrida;
    private javax.swing.JCheckBox jcFutebol;
    private javax.swing.JCheckBox jcNatacao;
    private javax.swing.JCheckBox jcPasseio;
    private javax.swing.JCheckBox jcTenis;
    private javax.swing.JCheckBox jcTrilha;
    private javax.swing.JCheckBox jcVolei;
    // End of variables declaration//GEN-END:variables
}
