/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pastime.cash;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author elisabeth_mello
 */
public class Login extends javax.swing.JFrame {

    private static int jaPassouAquiNome=0;
    private static int jaPassouAquiSenha=0;

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setSize(485,355);
        jaPassouAquiNome=0;
        jaPassouAquiSenha=0;
        //jNada.setVisible(false);
        //jNada.requestFocusInWindow();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jUsuario = new javax.swing.JTextField();
        jSenha = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jNada = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, -1, -1));

        jUsuario.setForeground(new java.awt.Color(204, 204, 204));
        jUsuario.setText("Usuário");
        jUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jUsuarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jUsuarioFocusLost(evt);
            }
        });
        getContentPane().add(jUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 220, 24));

        jSenha.setForeground(new java.awt.Color(204, 204, 204));
        jSenha.setText("Senha");
        jSenha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jSenhaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jSenhaFocusLost(evt);
            }
        });
        getContentPane().add(jSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 220, 24));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Não tenho uma conta");
        jLabel3.setToolTipText("");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 110, 14));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Esqueci minha senha");
        jLabel4.setToolTipText("");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 100, 14));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pastime/cash/Imagens/wlOGO.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 140, 100));

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Login");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 100, 50));

        jButton1.setBackground(new java.awt.Color(153, 255, 153));
        jButton1.setText("Entrar");
        jButton1.setBorder(null);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 110, 24));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pastime/cash/Imagens/fundo cadastro logado.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 515, -1));

        jNada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNadaActionPerformed(evt);
            }
        });
        getContentPane().add(jNada, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 20, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        Cadastro cadastro = new Cadastro();
        dispose();
        cadastro.setVisible(true);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String usuario = jUsuario.getText();
        String senha = jSenha.getText();
        String userPadrao = ArmazenaUsuario.usuarioPadrao;
        String passPadrao = ArmazenaUsuario.senhaPadrao;
        if (usuario.equals("Usuário") || senha.equals("Senha")){
            JOptionPane.showMessageDialog(null, "Preencha todos os campos!");
        }else if ((userPadrao.equals(usuario)) && (passPadrao.equals(senha))){ 
                ArmazenaUsuario.usuario=userPadrao;
                ArmazenaUsuario.nome="Admin";
                ArmazenaUsuario.basquete=true;
                ArmazenaUsuario.saldo=999.99;
                Lobby lobby = new Lobby();
                dispose();
                lobby.setVisible(true);
            }else if (ArmazenaUsuario.usuario.equals(usuario) && (ArmazenaUsuario.senha.equals(senha))){
                Lobby lobby = new Lobby();
                dispose();
                lobby.setVisible(true);
            }else {
                JOptionPane.showMessageDialog(null, "Usuário e senha invalidos!");
            }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jUsuarioFocusGained
        String nome = jUsuario.getText();
        if (nome.equals("Usuário")){
            jaPassouAquiNome=0;
        }
        switch (jaPassouAquiNome){
            case 0:
                jUsuario.setText("");
                jUsuario.setForeground(Color.black);
                jaPassouAquiNome=1;
                break;
        }
                
        
        //if(jaPassouAquiNome=true){
        //jUsuario.setText("");
        //jUsuario.setForeground(Color.black);
        //jaPassouAquiNome=false;
        
    }//GEN-LAST:event_jUsuarioFocusGained

    private void jSenhaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jSenhaFocusGained
        String senha = jSenha.getText();
        if (senha.equals("Senha")){
            jaPassouAquiSenha=0;
        }
        switch (jaPassouAquiSenha){
            case 0:
                jSenha.setText("");
                jSenha.setForeground(Color.black);
                jaPassouAquiSenha=1;
                break;
        }

        //if (jaPassouAquiSenha=false){
        //jSenha.setText("");
        //jSenha.setForeground(Color.black);
        //jaPassouAquiSenha=true;
        //}
    }//GEN-LAST:event_jSenhaFocusGained

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        Esqueci esqueci = new Esqueci();
        dispose();
        esqueci.setVisible(true);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jUsuarioFocusLost
        String usuario = jUsuario.getText();
        if (usuario.equals("")){
            jUsuario.setText("Usuário");
            jUsuario.setForeground(Color.gray);
        }
    }//GEN-LAST:event_jUsuarioFocusLost

    private void jSenhaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jSenhaFocusLost
        String senha = jSenha.getText();
        if (senha.equals("")){
            jSenha.setText("Senha");
            jSenha.setForeground(Color.gray);
        }
    }//GEN-LAST:event_jSenhaFocusLost

    private void jNadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNadaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jNada;
    private javax.swing.JPasswordField jSenha;
    private javax.swing.JTextField jUsuario;
    // End of variables declaration//GEN-END:variables
}
