/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panels;

/**
 *
 * @author eric_massaneiro
 */
public class Arena extends javax.swing.JPanel {

    /**
     * Creates new form Arena
     */
    public Arena() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel5.setText("Localização: Rua Inácio Bastos - Bucarein, Joinville - SC");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 54, -1, 30));

        jLabel4.setText("Custo médio R$40,00 o ingresso");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 44, -1, 20));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel3.setText("Arena Joinville");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, 10));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panels/imagens/Arena.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 90, 90));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panels/imagens/base panel a.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
